use crate::{core::posix::Posix, media::media_id::MediaId, user::user_id::UserId};

use super::{list_id::ListId, list_item_id::ListItemId};

pub struct List {
    id: ListId,
    created_at_posix: Posix,
    updated_at_posix: Posix,
    deleted_at_posix: Option<Posix>,
    name: String,
    description: String,
    creator_user_id: UserId,
    variant: ListVariant,
}

pub enum ListVariant {
    UserCreated,
    AutoGenerated,
}

pub struct ListItem {
    id: ListItemId,
    list_id: ListId,
    variant: ListItemVariant,
}

pub enum ListItemVariant {
    Media(MediaId),
}
